services:
  # PHPコンテナ
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: laravel_app:latest
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/work
    volumes:
      - ./src:/var/www/work               # ホストのsrcディレクトリをコンテナの作業ディレクトリにマウント
      - ./php/php.ini:/usr/local/etc/php/php.ini         # カスタムPHP設定をマウント
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini # カスタムXdebug設定をマウント
    ports:
      - "9000:9000"                        # PHP-FPMのポートを公開
    networks:
      - laravel

  # Nginxコンテナ
  web:
    image: nginx:1.21.6
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"                            # HTTPポートを公開
    volumes:
      - ./src:/var/www/work             # ホストのsrcディレクトリをコンテナのドキュメントルートにマウント
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # カスタムNginx設定をマウント
    depends_on:
      - app                                # PHPコンテナが先に起動するように設定
    networks:
      - laravel

  # PostgreSQLコンテナ
  db:
    image: postgres:17.2
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: laravel               # データベースユーザー名
      POSTGRES_PASSWORD: secret            # データベースパスワード
      POSTGRES_DB: laravel                  # デフォルトデータベース名
    ports:
      - "5432:5432"                        # PostgreSQLのポートを公開
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local